---
title: "Analysis of government trust and attitudes towards vaccines"
output: html_document
date: "2024-02-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# All libraries should be loaded at the top

library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
library(psych)

options(scipen = 999)

ed_levels = c(
  "Primary school",
  "Secondary school (age under 15 years old)",
  "GNVQ / GSVQ / GCSE/ SCE standard.",
  "NVQ1, NVQ2",
  "NVQ3/ SCE Higher Grade/ Advanced GNVQ/ GCE A/AS or similar.",
  "NVQ4 / HNC / HND / Bachelor's degree or similar.",
  "NVQ5 or post-graduate diploma."                             
)

likert_levels = c (
  "Strongly disagree",
  "Tend to disagree",
  "Neither agree nor disagree",
  "Tend to agree",
  "Strongly agree"             
)

d_trustvac = read_csv('../data/trust-vaccines.csv',
 col_types = cols(
   col_number(),
   col_factor(),
   col_factor(ordered = TRUE, levels = ed_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels),
   col_factor(ordered = TRUE, levels = likert_levels)
 ))

# We rebounded the dataframe to this new one and added new columns using mutate
# We can either add a new column and name it similar to this code 
#d_trustvac = d_trustvac %>% 
#  mutate(
#    govhonest_coded = govhonest %>% as.numeric,
#    govright_coded = govright %>% as.numeric
#  )

#Or we can make the original column numeric instead using this code
d_trustvac = d_trustvac %>% 
  mutate(
    across(
      .cols = c(starts_with('gov'), starts_with('vac')),
      .fns = as.numeric,
      .names = '{.col}_coded' # This is if i Want to keep the original columns 
    )
  )

keys_list = list(
  gov_trust = c(
    'govhonest_coded',
    'govright_coded',
    '-govunfair_coded', #we add (-) cause the values have negative connotation eg. unfair..etc
    '-govignore_coded',
    '-govcautious_coded',
    '-govxbel_coded'
  ),
  vac_attitude = c(
    'vacch_coded',
    'vacsafe_coded',
    'vacwork_coded'
  )
)


#If we write in the console '?' followed by the function eg.. '?scoreItems' we will get the arguments 

trustvac_scores = scoreItems(
  keys = keys_list,
  items = d_trustvac,
  totals = FALSE,
  missing = TRUE,
  impute = 'none' #impute is important if you're calculating totals not averages
)

d_trustvac = cbind(d_trustvac, trustvac_scores$scores)
```

# Demographic characteristics of the sample

## Age
```{r}
d_trustvac %>%
  summarise(
    n = n(),
    M = mean(age) %>% round(digits = 2),
    Mdn = median(age),
    SD = sd(age) %>% round(digits = 2)
  )

d_trustvac %>%
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 5)
```
## Gender
```{r}
d_trustvac %>%
  count(gender_nb)

d_trustvac %>%
  ggplot(aes(x = gender_nb)) +
  geom_bar()
```

## Highest educational qualification 
```{r}
d_trustvac %>%
  count(hhedqual)

d_trustvac %>%
  ggplot(aes(x = hhedqual)) +
  geom_bar() +
  coord_flip()
```

# Desriptive Statistics: Likert Items

```{r}
# We use tibble to transform it to a dataframe 
#tibble(
#  d_trustvac$govhonest, 
#  as.numeric(d_trustvac$govhonest)) %>% #transforming it to numeric data
#  kable # to transform it to a table as follows

trustvac_likert_summary = d_trustvac %>%
  select(ends_with('_coded')) %>%
  lapply( #This goes through each column of th dataframe 
    median, na.rm = TRUE
  ) 
trustvac_likert_summary

d_trustvac_likert_summary = tibble(
  Item = trustvac_likert_summary %>% names, 
  Median = trustvac_likert_summary %>% unlist
)

d_trustvac_likert_summary

d_trustvac_likert_summary %>%
  ggplot(aes(x = Item, y = Median)) +
  geom_point() +
  coord_flip()
```



```{r}

d_trustvac = d_trustvac %>%
  mutate(
    Female = gender_nb == 'Female',
    Vaccines_safe = vacsafe %>% 
      recode(
        'Tend to agree' = TRUE, 
        'Strongly agree' = TRUE,
        'Neither agree nor disagree' = FALSE,
        'Tend to disagree' = FALSE, 
        'Strongly disagree' = FALSE)
  )
d_trustvac %>%
  xtabs(~ Female + Vaccines_safe, .)

d_trustvac %>% 
  group_by(Female) %>%
  summarise(
    n = n(),
    Agree = sum(Vaccines_safe > 3, na.rm = TRUE)
  ) %>% 
  mutate(
    Percentage = round(Agree / n*100)
  )

chisq.test(
  d_trustvac$Female,
  d_trustvac$Vaccines_safe
)
fisher.test(
  d_trustvac$Female,
  d_trustvac$Vaccines_safe
)
```

```{r}
d_trustvac %>%
  wilcox.test(
    vacsafe_coded ~ Female,
    data = .
  )
```

```{r}
d_trustvac %>%
  t.test(
    age ~ Vaccines_safe,
    var.equal = FALSE,
    data = .
  )
```

